[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "any", "--transition-fps", "60"]
set = true

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'
