# --- MONITORS --- #
monitor=,preferred,auto,1.25

# monitor=eDP-1,disable
# monitor=HDMI-A-1,5120x2160@30,0x0,2


# --- MY PROGRAMS --- #
$terminal = ghostty
$fileManager = nautilus
$menu = rofi -show drun


# --- AUTOSTART --- #
exec-once = waybar
exec-once = awww-daemon
exec-once = swaync
exec-once = sleep 2 && kanshi


# --- ENVIRONMENT VARIABLES --- #
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = WLR_RENDERER_ALLOW_SOFTWARE,0


# --- TAGS --- #
# source= ~/.config/hypr/configs/tags.conf


# --- LOOK AND FEEL --- #
source= ~/.config/hypr/configs/look_and_feel.conf


# --- ANIMATIONS --- #
source= ~/.config/hypr/configs/animations.conf


# --- WINDOW & LAYER RULES --- #
source= ~/.config/hypr/configs/window_rules.conf


dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    vfr = true
}

render {
    new_render_scheduling = true
}

xwayland {
    force_zero_scaling = true
}


# --- INPUT --- #
source= ~/.config/hypr/configs/input.conf


# --- KEYBINDINGS --- #
source= ~/.config/hypr/configs/keybindings.conf
